//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int FK_Id_coullege { get; set; }
        public int FK_Id_professser { get; set; }
    
        public virtual college college { get; set; }
        public virtual professor professor { get; set; }
    }
}
